table:
  name: commandcenter_reportconfiguration
  schema: public
configuration:
  comment: null
  custom_column_names:
    border_color: borderColor
    border_weight: borderWeight
    default_docx_template_id: docxTemplateId
    default_pptx_template_id: pptxTemplateId
    enable_borders: enableBorders
    label_figure: labelFigure
    label_table: labelTable
    prefix_figure: prefixFigure
    prefix_table: prefixTable
  custom_name: reportConfiguration
  custom_root_fields: {}
object_relationships:
- name: docxTemplate
  using:
    foreign_key_constraint_on: default_docx_template_id
- name: pptxTemplate
  using:
    foreign_key_constraint_on: default_pptx_template_id
select_permissions:
- permission:
    columns:
    - id
    - border_weight
    - border_color
    - prefix_figure
    - prefix_table
    - default_docx_template_id
    - default_pptx_template_id
    - enable_borders
    - label_figure
    - label_table
    filter: {}
  role: manager
- permission:
    columns:
    - default_docx_template_id
    - default_pptx_template_id
    - id
    - enable_borders
    - border_color
    - label_figure
    - label_table
    - prefix_figure
    - prefix_table
    - border_weight
    filter: {}
  role: restricted
- permission:
    columns:
    - default_docx_template_id
    - default_pptx_template_id
    - id
    - enable_borders
    - border_color
    - label_figure
    - label_table
    - prefix_figure
    - prefix_table
    - border_weight
    filter: {}
  role: user
