# Generated by Django 4.2 on 2025-07-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commandcenter", "0035_extrafieldmodel_is_collab_editable"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enable",
                    models.BooleanField(
                        default=False,
                        help_text="Enable to allow AI-based finding generation",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        default="LLM API Key",
                        help_text="API key for the LLM provider",
                        max_length=255,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        default="gpt-3.5-turbo",
                        help_text="Model name to use for generation",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "LLM Configuration",
            },
        ),
    ]
